#Master docker file should be inherited from the base image and should expose port 60000.
FROM sridharc20/jmbase
MAINTAINER Sridhar.C
# Ports to be exposed from the container for JMeter Master
EXPOSE 60000

